### PR TITLE
A few small corrections and finished translating settings

### PR DESCRIPTION
**Pull request by 1JorgeB**

### CODE REVIEW

**Comment by spencerjunraid** [comment]
@johnnieblack - I'm getting "this branch has conflicts that must be resolved" and cannot merge. I will need to look into this further...

**Comment by 1JorgeB** [comment]
Yes, got those also when I created the pull request, but don't know how to
fix it, looks like someone else is also doing some translations, and some
of mine are duplicates

**Comment by spencerjunraid** [comment]
Hmm. Ok- bringing in a pro for help.

@bergware - Do you know why there are "conflicts" and how to resolve them so I can merge here? Sorry, I will learn quickly as a padawan. :-P

**Comment by bergware** [comment]
I resolved the conflicts. Not sure what happened, it looks like some sync problem.

Make sure to sync first before submitting a next PR

**Comment by spencerjunraid** [comment]
Thank you Ronald.

**Pull request merged**
